# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

AOSP_IMAGE = File.join(File.dirname(File.expand_path(__FILE__)), 'aosp.vmdk')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.box_check_update = false

  # android ddms port
  config.vm.network :forwarded_port, guest: 8700, host: 8700 

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]

    unless File.exist?(AOSP_IMAGE)
      # 80GB aosp.vmdk
      vb.customize ['createhd', '--filename', AOSP_IMAGE, '--size', 81920, '--format', 'VMDK']
    end
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', AOSP_IMAGE]
  end

  config.vm.provision :shell, :path => "aosp.sh"
end
